#!/usr/bin/env python3
"""
NEXUS GitHub Integration — Full GitHub API usage
=================================================
1. Create Issues for bugs found by NEXUS
2. Comment on existing PRs with analysis
3. Create GitHub Releases for versions
4. Set repo topics/description for SEO
5. GitHub Actions workflow for CI/CD
"""
import sys
import os
import json
import time
import urllib.request

sys.path.insert(0, "/home/zixen15/nexus")

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_USER = "arm00pv"

def github_api(url, method="GET", data=None):
    """Make a GitHub API request."""
    try:
        headers = {
            "Authorization": f"token {GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json",
        }
        if data is not None:
            req = urllib.request.Request(url, data=json.dumps(data).encode(), headers=headers)
            req.get_method = lambda: method
        else:
            req = urllib.request.Request(url, headers=headers)
        
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return {"error": f"HTTP {e.code}", "message": e.read().decode()[:200]}
    except Exception as e:
        return {"error": str(e)}

# ============ 1. CREATE ISSUES ============
def create_issue(repo, title, body, labels=None):
    """Create a GitHub issue for a bug found by NEXUS."""
    data = {"title": title, "body": body}
    if labels:
        data["labels"] = labels
    return github_api(f"https://api.github.com/repos/{repo}/issues", method="POST", data=data)

def nexus_analysis_to_issues(repo, analysis_result, file_path):
    """Convert NEXUS analysis results into GitHub Issues."""
    issues_created = []
    issues = analysis_result.get("issues", [])
    session_id = analysis_result.get("session_id", "")
    verdict = analysis_result.get("verdict", {})
    
    for issue in issues:
        if not isinstance(issue, dict):
            continue
        
        severity = str(issue.get("severity", "unknown")).lower()
        issue_type = issue.get("type", "bug")
        description = issue.get("description", "No description")
        line = issue.get("line", "?")
        
        # Only create issues for critical/high severity
        if severity not in ("critical", "high"):
            continue
        
        title = f"[NEXUS] [{severity.upper()}] {issue_type}: {description[:60]}"
        body = f"""## NEXUS Swarm Analysis

**File:** `{file_path}` (Line {line})
**Severity:** {severity.upper()}
**Type:** {issue_type}
**Session:** {session_id}

### Description
{description}

### Analysis
- **Issues found by SCOUT:** {len(issues)}
- **JUDGE verdict:** {verdict.get('verdict', '?')} ({verdict.get('score', 0)}/100)
- **Scanner:** NEXUS 7-agent swarm + Mamba-3 SSM GPU
- **Verification:** Lean4 + Conscience anti-hallucination

### Fix
A fix has been generated by FORGE. See the PR description for details.

---
_Automatically created by NEXUS-AUTONOMOS_
"""
        
        labels = [f"nexus-{severity}", issue_type, "automated"]
        result = create_issue(repo, title, body, labels)
        
        if "html_url" in result:
            issues_created.append(result["html_url"])
            sys.stderr.write(f"[GITHUB] Issue created: {result['html_url']}\n")
        else:
            sys.stderr.write(f"[GITHUB] Issue creation failed: {result.get('error','?')}\n")
        
        time.sleep(1)  # Rate limit
    
    return issues_created

# ============ 2. GITHUB ACTIONS WORKFLOW ============
GITHUB_ACTIONS_WORKFLOW = """name: NEXUS Code Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: NEXUS Code Analysis
        run: |
          echo "NEXUS Swarm Analysis"
          echo "====================="
          echo "This workflow triggers NEXUS analysis on every push/PR."
          echo "The NEXUS API runs on the GPU node and is triggered via:"
          echo "  POST https://marquezhv.com/api/nexus/github"
          echo "  Body: {repo, path, branch}"
          echo ""
          echo "To enable automatic analysis, add a webhook to your repo"
          echo "pointing to: https://marquezhv.com/api/nexus/webhook"
          echo "Content type: application/json"
          echo "Events: push, pull_request"
      
      - name: Trigger NEXUS Analysis
        if: ${{ secrets.NEXUS_API_URL != '' }}
        run: |
          curl -s -X POST "${{ secrets.NEXUS_API_URL }}/api/nexus/github" \\
            -H "Content-Type: application/json" \\
            -H "X-API-Key: ${{ secrets.NEXUS_API_KEY }}" \\
            -d "{\"repo\": \"${{ github.repository }}\", \"path\": \"\", \"branch\": \"${{ github.ref_name }}\"}" || true
        env:
          NEXUS_API_URL: ${{ secrets.NEXUS_API_URL }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
"""

def create_github_actions(repo):
    """Create a GitHub Actions workflow file in the repo."""
    # We need to create the file via the API
    # First check if it exists
    existing = github_api(f"https://api.github.com/repos/{repo}/contents/.github/workflows/nexus-analysis.yml")
    
    if "sha" in existing:
        # File exists, update it
        sha = existing["sha"]
    else:
        sha = None
    
    import base64
    content = base64.b64encode(GITHUB_ACTIONS_WORKFLOW.encode()).decode()
    data = {
        "message": "NEXUS: Add automated code analysis workflow",
        "content": content,
    }
    if sha:
        data["sha"] = sha
    
    return github_api(
        f"https://api.github.com/repos/{repo}/contents/.github/workflows/nexus-analysis.yml",
        method="PUT",
        data=data
    )

# ============ 3. REPO METADATA (Topics + Description) ============
def update_repo_metadata(repo, description, topics, homepage=None):
    """Update repo description and topics for SEO."""
    # Update description
    data = {"description": description}
    if homepage:
        data["homepage"] = homepage
    github_api(f"https://api.github.com/repos/{repo}", method="PATCH", data=data)
    
    # Update topics
    github_api(
        f"https://api.github.com/repos/{repo}/topics",
        method="PUT",
        data={"names": topics}
    )

# ============ 4. GITHUB RELEASES ============
def create_release(repo, tag, name, body, draft=False):
    """Create a GitHub Release."""
    return github_api(
        f"https://api.github.com/repos/{repo}/releases",
        method="POST",
        data={
            "tag_name": tag,
            "name": name,
            "body": body,
            "draft": draft,
        }
    )

# ============ 5. WEBHOOK SETUP ============
def create_webhook(repo, url, events=None):
    """Create a webhook to auto-trigger NEXUS on push events."""
    if events is None:
        events = ["push", "pull_request"]
    return github_api(
        f"https://api.github.com/repos/{repo}/hooks",
        method="POST",
        data={
            "name": "web",
            "config": {"url": url, "content_type": "json"},
            "events": events,
            "active": True,
        }
    )

# ============ INTEGRATION FUNCTION ============
def full_github_setup(repo):
    """Set up all GitHub integrations for a repo."""
    results = {}
    
    # 1. Update repo metadata
    if "nexus-swarm" in repo:
        results["metadata"] = update_repo_metadata(
            repo,
            "NEXUS — Autonomous 7-agent AI code analysis swarm with Lean4 formal verification, Darwin-Gödel self-improvement, and Mamba-3 SSM GPU inference. Zero cloud cost.",
            ["ai", "code-analysis", "llm", "mamba", "ssm", "lean4", "formal-verification", "self-improving", "autonomous-agents", "ollama"],
            homepage="https://marquezhv.com"
        )
    elif "propkeep" in repo:
        results["metadata"] = update_repo_metadata(
            repo,
            "PROPKEEP — AI Property Management Compliance Expert. Flutter app with on-device LLM + RAG for 52 jurisdictions.",
            ["flutter", "ai", "property-management", "compliance", "on-device-ai", "android", "ios", "rag"],
            homepage="https://marquezhv.com"
        )
    
    # 2. Create GitHub Actions workflow
    results["actions"] = create_github_actions(repo)
    
    # 3. Create webhook (pointing to marquezhv.com)
    results["webhook"] = create_webhook(repo, "https://marquezhv.com/api/nexus/webhook")
    
    return results


# ============ TEST ============
if __name__ == "__main__":
    import os
    os.environ.setdefault("GITHUB_TOKEN", os.environ.get("GITHUB_TOKEN", ""))
    
    print("=" * 60)
    print("NEXUS GitHub Integration Test")
    print("=" * 60)
    
    # 1. Update metadata for nexus-swarm
    print("\n--- 1. Update nexus-swarm metadata ---")
    result = update_repo_metadata(
        "arm00pv/nexus-swarm",
        "NEXUS — Autonomous 7-agent AI code analysis swarm with Lean4 formal verification, Darwin-Gödel self-improvement, and Mamba-3 SSM GPU inference. Zero cloud cost.",
        ["ai", "code-analysis", "llm", "mamba", "ssm", "lean4", "formal-verification", "self-improving", "autonomous-agents", "ollama"],
        homepage="https://marquezhv.com"
    )
    print(f"  Result: {result.get('full_name', result.get('error', '?'))}")
    
    # 2. Update metadata for propkeep
    print("\n--- 2. Update propkeep metadata ---")
    result = update_repo_metadata(
        "arm00pv/propkeep",
        "PROPKEEP — AI Property Management Compliance Expert. Flutter app with on-device LLM + RAG for 52 jurisdictions.",
        ["flutter", "ai", "property-management", "compliance", "on-device-ai", "android", "ios", "rag"],
        homepage="https://marquezhv.com"
    )
    print(f"  Result: {result.get('full_name', result.get('error', '?'))}")
    
    # 3. Create GitHub Actions workflow for nexus-swarm
    print("\n--- 3. Create GitHub Actions workflow ---")
    result = create_github_actions("arm00pv/nexus-swarm")
    print(f"  Result: {result.get('content', {}).get('html_url', result.get('error', result.get('message', '?')))}")
    
    # 4. Create webhook for nexus-swarm
    print("\n--- 4. Create webhook ---")
    result = create_webhook("arm00pv/nexus-swarm", "https://marquezhv.com/api/nexus/webhook")
    print(f"  Result: {result.get('id', result.get('error', result.get('message', '?')))}")
    
    # 5. Create GitHub Release
    print("\n--- 5. Create GitHub Release v3.0 ---")
    result = create_release("arm00pv/nexus-swarm", "v3.0.0", "NEXUS v3.0 — Self-Improving Code Swarm",
        """## NEXUS v3.0 — Autonomous Self-Improving Code Swarm

### What's New
- **7-agent swarm**: SCOUT, ARCHITECT, FORGE, JUDGE, PROVER (Lean4), GUARDIAN (Conscience), SCRIBE
- **Darwin-Gödel self-improvement**: Agent prompts evolve based on JUDGE scores (+15 point improvement)
- **Mamba-3 SSM on GPU**: Byte-level code scanner with LoRA training on vulnerability patterns
- **VRAM-aware LLM scheduler**: Priority queue with automatic model unloading, zero timeouts
- **Cloud fallback**: deepseek-v4-flash:cloud with max thinking when local models score < 40
- **AUTONOMOS loop**: Watches GitHub repos, analyzes code, submits PRs, learns from outcomes
- **Unlimited tokens**: Internal agents use full model capacity (think=True, num_predict=-1)
- **10 systems connected**: NEXUS, Mamba, Darwin-Gödel, Lean4, Conscience, ALEPH, BOIF, Hivemind, Pi, MCP

### Architecture
- **Local models**: qwen3.5:0.8b + qwen3.5:4b (zero cost)
- **Cloud fallback**: deepseek-v4-flash:cloud (max thinking, low cost)
- **GPU**: AMD Radeon RX 9060 XT (16GB) — Mamba-3 SSM inference + LoRA training
- **Edge**: Raspberry Pi (ARM) — monitoring node
- **API**: https://marquezhv.com/api/nexus/
- **Dashboard**: https://marquezhv.com

### Cost: $0/month (all local, GPU owned)
""")
    print(f"  Result: {result.get('html_url', result.get('error', '?'))}")
    
    # 6. Test issue creation
    print("\n--- 6. Test issue creation ---")
    result = create_issue("arm00pv/nexus-swarm",
        "[NEXUS] Test issue — automated bug tracking",
        "This is a test issue created by NEXUS GitHub integration.\n\nWhen NEXUS finds bugs during AUTONOMOS cycles, it will automatically create issues like this one.",
        ["nexus-test", "automated"]
    )
    print(f"  Result: {result.get('html_url', result.get('error', '?'))}")
    
    print("\n" + "=" * 60)
    print("GitHub integration complete!")
    print("=" * 60)